version: 2
updates:
  - package-ecosystem: nuget
    directory: /
    schedule:
      interval: weekly
    open-pull-requests-limit: 3
    target-branch: dev
    groups:
      nuget-non-major:
        update-types:
          - "minor"
          - "patch"

  - package-ecosystem: cargo
    directory: /engine
    schedule:
      interval: weekly
    open-pull-requests-limit: 3
    target-branch: dev
    groups:
      cargo-non-major:
        update-types:
          - "minor"
          - "patch"

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
    open-pull-requests-limit: 3
    target-branch: dev
    groups:
      actions-non-major:
        update-types:
          - "minor"
          - "patch"
