using System.Text;
using optiCombat.Services;

namespace optiCombat.Tests;

public sealed class FreshclamConfSupportTests : IDisposable
{
    private readonly string _root;
    private readonly List<string> _paths = new();

    public FreshclamConfSupportTests()
    {
        _root = Path.Combine(Path.GetTempPath(), "opticombat_fc_" + Guid.NewGuid().ToString("N"));
        Directory.CreateDirectory(_root);
    }

    public void Dispose()
    {
        foreach (var p in _paths)
        {
            try { if (File.Exists(p)) File.Delete(p); } catch { }
            try { if (File.Exists(p + ".v1.bak")) File.Delete(p + ".v1.bak"); } catch { }
        }
        try { Directory.Delete(_root, recursive: true); } catch { }
    }

    private string TempConf(string name)
    {
        var path = Path.Combine(_root, name);
        _paths.Add(path);
        return path;
    }

    [Fact]
    public void HasUtf8Bom_detects_bom_prefix()
    {
        var path = TempConf("bom.conf");
        File.WriteAllBytes(path, new byte[] { 0xEF, 0xBB, 0xBF, (byte)'#' });
        Assert.True(FreshclamConfSupport.HasUtf8Bom(path));
    }

    [Fact]
    public void IsOurManagedConf_recognizes_opticombat_marker()
    {
        Assert.True(FreshclamConfSupport.IsOurManagedConf("# freshclam.conf generated by optiCombat v6\n"));
        Assert.False(FreshclamConfSupport.IsOurManagedConf("DatabaseDirectory \"/tmp\"\n"));
    }

    [Fact]
    public void BuildConfBytes_has_no_bom_and_includes_marker()
    {
        var bytes = FreshclamConfSupport.BuildConfBytes(6, "C:/db", "C:/log/freshclam.log", false, null);
        Assert.NotNull(bytes);
        Assert.False(bytes!.Length >= 3 && bytes[0] == 0xEF);
        var text = Encoding.UTF8.GetString(bytes);
        Assert.Contains("generated by optiCombat v6", text, StringComparison.OrdinalIgnoreCase);
        Assert.Contains("DatabaseDirectory", text);
    }

    [Fact]
    public void InvalidateIfLegacy_renames_unmanaged_conf()
    {
        var path = TempConf("legacy.conf");
        File.WriteAllText(path, "DatabaseDirectory \"/old\"\n");
        FreshclamConfSupport.InvalidateIfLegacy(path);
        Assert.False(File.Exists(path));
        Assert.True(File.Exists(path + ".v1.bak"));
    }

    [Fact]
    public void EnsureWritableConf_prefers_localappdata_path()
    {
        var preferred = TempConf("preferred.conf");
        var install = TempConf("install.conf");
        var result = FreshclamConfSupport.EnsureWritableConf(
            preferred,
            install,
            _ => FreshclamConfSupport.BuildConfBytes(1, "C:/db", "C:/log", false, null));
        Assert.Equal(preferred, result);
        Assert.True(FreshclamConfSupport.IsOurManagedConf(File.ReadAllText(preferred)));
    }

}
