using System.IO;
using System.Text;

namespace optiCombat.Services
{
    /// <summary>Génère clamd.conf géré par optiCombat (TCP local).</summary>
    internal static class ClamdConfSupport
    {
        public const int DefaultTcpPort = 3310;

        public static string GetConfPath() =>
            Path.Combine(
                Environment.GetFolderPath(Environment.SpecialFolder.LocalApplicationData),
                "optiCombat", "clamd", "clamd.conf");

        public static string GetPidPath() =>
            Path.Combine(
                Environment.GetFolderPath(Environment.SpecialFolder.LocalApplicationData),
                "optiCombat", "clamd", "clamd.pid");

        public static string GetLogPath() =>
            Path.Combine(
                Environment.GetFolderPath(Environment.SpecialFolder.LocalApplicationData),
                "optiCombat", "clamd", "clamd.log");

        public static void EnsureConf(string databaseDir, IEnumerable<string>? excludePatterns = null)
        {
            var confPath = GetConfPath();
            var dir = Path.GetDirectoryName(confPath)!;
            if (!Directory.Exists(dir))
                Directory.CreateDirectory(dir);

            var db = FreshclamConfSupport.NormalizePathForConf(databaseDir);
            var log = FreshclamConfSupport.NormalizePathForConf(GetLogPath());
            var pid = FreshclamConfSupport.NormalizePathForConf(GetPidPath());

            var sb = new StringBuilder();
            sb.AppendLine("# generated by optiCombat");
            sb.AppendLine("LogFile " + log);
            sb.AppendLine("PidFile " + pid);
            sb.AppendLine("DatabaseDirectory " + db);
            sb.AppendLine("TCPSocket " + DefaultTcpPort);
            sb.AppendLine("TCPAddr 127.0.0.1");
            sb.AppendLine("Foreground yes");
            sb.AppendLine("StreamMaxLength 100M");
            if (excludePatterns != null)
            {
                foreach (var pattern in excludePatterns)
                {
                    if (!string.IsNullOrWhiteSpace(pattern))
                        sb.AppendLine("ExcludePath " + pattern);
                }
            }

            File.WriteAllText(confPath, sb.ToString(), new UTF8Encoding(encoderShouldEmitUTF8Identifier: false));
        }
    }
}
