using System.IO;
using System.Text;
using System.Text.RegularExpressions;

namespace optiCombat.Services
{
    /// <summary>
    /// Logique pure freshclam.conf (BOM, marqueur optiCombat, invalidation legacy).
    /// Partagée entre <see cref="FreshclamUpdater"/> et les tests unitaires.
    /// </summary>
    internal static class FreshclamConfSupport
    {
        private static readonly Regex ManagedConfMarker = new(
            @"generated\s+by\s+optiCombat\s+v\d+",
            RegexOptions.IgnoreCase | RegexOptions.Compiled);

        /// <summary>Détecte le BOM UTF-8 (0xEF 0xBB 0xBF) en tête de fichier.</summary>
        public static bool HasUtf8Bom(string path)
        {
            try
            {
                using var fs = new FileStream(path, FileMode.Open, FileAccess.Read, FileShare.Read);
                if (fs.Length < 3) return false;
                var bom = new byte[3];
                _ = fs.Read(bom, 0, 3);
                return bom[0] == 0xEF && bom[1] == 0xBB && bom[2] == 0xBF;
            }
            catch
            {
                return false;
            }
        }

        /// <summary>Conf généré par optiCombat (marqueur de version dans le commentaire d'en-tête).</summary>
        public static bool IsOurManagedConf(string content) =>
            !string.IsNullOrEmpty(content) && ManagedConfMarker.IsMatch(content);

        /// <summary>
        /// Directive rejetée par ClamAV 1.4+ (« Can't open/parse freshclam.conf »).
        /// Les certificats CVD passent exclusivement par la variable d'environnement <c>CVD_CERTS_DIR</c>.
        /// </summary>
        public const string ObsoleteCvdCertsDirective = "CVDCertsDirectory";

        /// <summary>Vrai si le contenu contient une directive obsolète (conf à régénérer).</summary>
        public static bool ContainsObsoleteDirective(string content) =>
            !string.IsNullOrEmpty(content)
            && content.Contains(ObsoleteCvdCertsDirective, StringComparison.OrdinalIgnoreCase);

        /// <summary>
        /// Si le fichier existe mais n'est pas géré par optiCombat, ou contient une directive
        /// obsolète (<see cref="ObsoleteCvdCertsDirective"/>), le renomme en .v1.bak
        /// (ou le supprime) pour forcer une régénération propre.
        /// </summary>
        public static void InvalidateIfLegacy(string confPath)
        {
            try
            {
                if (!File.Exists(confPath)) return;

                var content = File.ReadAllText(confPath);
                if (IsOurManagedConf(content) && !ContainsObsoleteDirective(content))
                    return;

                var bak = confPath + ".v1.bak";
                try
                {
                    if (File.Exists(bak)) File.Delete(bak);
                    File.Move(confPath, bak);
                    AppLogger.Info("FreshclamConfSupport",
                        $"Conf legacy renommé en {Path.GetFileName(bak)} — régénération à venir");
                }
                catch (Exception ex)
                {
                    try { File.Delete(confPath); }
                    catch { AppLogger.Warn("FreshclamConfSupport", $"Conf legacy non remplaçable: {confPath}", ex); }
                }
            }
            catch (Exception ex)
            {
                AppLogger.Warn("FreshclamConfSupport", $"InvalidateIfLegacy {confPath}", ex);
            }
        }

        /// <summary>Normalise un chemin Windows pour freshclam.conf (slashes avant).</summary>
        public static string NormalizePathForConf(string path) => path.Replace('\\', '/');

        /// <summary>
        /// Échappe un chemin pour une directive freshclam entre guillemets.
        /// Rejette (null) si le chemin contient un retour ligne ou est vide.
        /// </summary>
        public static string? EscapePathForConf(string? path)
        {
            if (string.IsNullOrWhiteSpace(path))
                return null;

            if (path.IndexOfAny(['\r', '\n', '\0']) >= 0)
                return null;

            // freshclam : chaîne entre "…" — doubler les guillemets internes.
            return NormalizePathForConf(path).Replace("\"", "\"\"", StringComparison.Ordinal);
        }

        /// <summary>
        /// Construit le contenu ASCII/UTF-8 sans BOM. Retourne null si un BOM est détecté dans le buffer
        /// ou si un chemin contient un caractère interdit.
        /// Aucune directive de certificats : voir <see cref="ObsoleteCvdCertsDirective"/>.
        /// </summary>
        public static byte[]? BuildConfBytes(
            int confMarkerMajor,
            string databaseDirForConf,
            string logPathForConf)
        {
            var db = EscapePathForConf(databaseDirForConf);
            var log = EscapePathForConf(logPathForConf);
            if (db is null || log is null)
                return null;

            var lines = new List<string>
            {
                $"# freshclam.conf generated by optiCombat v{confMarkerMajor}",
                $"DatabaseDirectory \"{db}\"",
            };

            lines.AddRange(new[]
            {
                $"UpdateLogFile \"{log}\"",
                "LogTime yes",
                "LogVerbose no",
                "DatabaseMirror database.clamav.net",
                "MaxAttempts 3",
                "ConnectTimeout 30",
                // 0 = pas de timeout de lecture : le process a déjà un plafond applicatif.
                "ReceiveTimeout 0",
                // clamd charge déjà la base : la retester en RAM fait souvent échouer la MAJ.
                "TestDatabases no",
            });

            var content = string.Join("\n", lines) + "\n";
            var bytes = new UTF8Encoding(encoderShouldEmitUTF8Identifier: false).GetBytes(content);

            if (bytes.Length >= 3 && bytes[0] == 0xEF && bytes[1] == 0xBB && bytes[2] == 0xBF)
                return null;

            return bytes;
        }

        /// <summary>
        /// Stratégie EnsureConfExists : LocalAppData d'abord, puis conf à côté de l'exécutable.
        /// </summary>
        public static string? EnsureWritableConf(
            string preferredConfPath,
            string installConfPath,
            Func<string, byte[]?> buildBytesForPath,
            Action<string>? onLegacyBomRepaired = null)
        {
            InvalidateIfLegacy(preferredConfPath);
            InvalidateIfLegacy(installConfPath);

            var primary = TryWriteConfAt(preferredConfPath, buildBytesForPath);
            if (primary != null)
            {
                TryRepairLegacyBom(installConfPath, buildBytesForPath, onLegacyBomRepaired);
                return primary;
            }

            return TryWriteConfAt(installConfPath, buildBytesForPath);
        }

        /// <summary>Écrit des octets sans BOM ; retourne le chemin ou null.</summary>
        public static string? TryWriteConfAt(string targetPath, byte[] bytes)
        {
            try
            {
                var dir = Path.GetDirectoryName(targetPath);
                if (!string.IsNullOrEmpty(dir))
                    Directory.CreateDirectory(dir);

                try { if (File.Exists(targetPath)) File.Delete(targetPath); }
                catch (UnauthorizedAccessException) { }
                catch (IOException) { }

                File.WriteAllBytes(targetPath, bytes);

                if (HasUtf8Bom(targetPath))
                {
                    try { File.Delete(targetPath); } catch { /* best effort */ }
                    return null;
                }

                return targetPath;
            }
            catch (UnauthorizedAccessException ex)
            {
                AppLogger.Warn("FreshclamConfSupport", $"TryWriteConfAt {targetPath}: accès refusé", ex);
                return null;
            }
            catch (Exception ex)
            {
                AppLogger.Error("FreshclamConfSupport", $"TryWriteConfAt {targetPath}", ex);
                return null;
            }
        }

        private static string? TryWriteConfAt(string targetPath, Func<string, byte[]?> buildBytesForPath)
        {
            var bytes = buildBytesForPath(targetPath);
            return bytes == null ? null : TryWriteConfAt(targetPath, bytes);
        }

        private static void TryRepairLegacyBom(
            string installConfPath,
            Func<string, byte[]?> buildBytesForPath,
            Action<string>? onRepaired)
        {
            try
            {
                if (!File.Exists(installConfPath) || !HasUtf8Bom(installConfPath))
                    return;

                if (TryWriteConfAt(installConfPath, buildBytesForPath) != null)
                {
                    onRepaired?.Invoke(installConfPath);
                    return;
                }

                var bak = installConfPath + ".bom-corrupt.bak";
                try
                {
                    if (File.Exists(bak)) File.Delete(bak);
                    File.Move(installConfPath, bak);
                }
                catch (Exception ex)
                {
                    AppLogger.Warn("FreshclamConfSupport", "TryRepairLegacyBom : renommage", ex);
                }
            }
            catch (Exception ex)
            {
                AppLogger.Warn("FreshclamConfSupport", "TryRepairLegacyBom", ex);
            }
        }
    }
}
